deb: make  postinst nspawn compatible

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,9 +1,52 @@
-#!/usr/bin/env bash
+#!/bin/sh
+
 set -euo pipefail
 
-systemctl daemon-reload
-systemctl enable log2ram.service log2ram-daily.timer
+# Automatically added by dh_installsystemd/13.2~bpo10+1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	# This will only remove masks created by d-s-h on package removal.
+	deb-systemd-helper unmask 'log2ram.service' >/dev/null || true
+	deb-systemd-helper unmask 'log2ram-daily.timer' >/dev/null || true
 
+	# was-enabled defaults to true, so new installations run enable.
+	if deb-systemd-helper --quiet was-enabled 'log2ram.service'; then
+		# Enables the unit on first installation, creates new
+		# symlinks on upgrades if the unit file has changed.
+		deb-systemd-helper enable 'log2ram.service' >/dev/null || true
+	else
+		# Update the statefile to add new symlinks (if any), which need to be
+		# cleaned up on purge. Also remove old symlinks.
+		deb-systemd-helper update-state 'log2ram.service' >/dev/null || true
+	fi
+
+	# was-enabled defaults to true, so new installations run enable.
+	if deb-systemd-helper --quiet was-enabled 'log2ram-daily.timer'; then
+		# Enables the unit on first installation, creates new
+		# symlinks on upgrades if the unit file has changed.
+		deb-systemd-helper enable 'log2ram-daily.timer' >/dev/null || true
+	else
+		# Update the statefile to add new symlinks (if any), which need to be
+		# cleaned up on purge. Also remove old symlinks.
+		deb-systemd-helper update-state 'log2ram-daily.timer' >/dev/null || true
+	fi
+
+fi
+# End automatically added section
+# Automatically added by dh_installsystemd/13.2~bpo10+1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if [ -d /run/systemd/system ]; then
+		systemctl --system daemon-reload >/dev/null || true
+		if [ -n "$2" ]; then
+			_dh_action=restart
+		else
+			_dh_action=start
+		fi
+		deb-systemd-invoke $_dh_action 'log2ram.service' >/dev/null || true
+		deb-systemd-invoke $_dh_action 'log2ram-daily.timer' >/dev/null || true
+	fi
+fi
+
+# End automatically added section
 
 rm -f /etc/cron.daily/log2ram
 rm -f /etc/cron.hourly/log2ram
@@ -12,5 +55,3 @@ if [ "$1" == "configure" ]; then
 	echo "#####         Reboot to activate log2ram         #####"
 	echo "##### edit /etc/log2ram.conf to configure options ####"
 fi
-
-exit 0
